### ISSUE TITLE
Typo in sid 3321316

### ISSUE THREAD

**Issue by jufajardini** [woundride/pawpatrules#2]
I was made aware of this through a Suricata post forum: https://forum.suricata.io/t/bad-option-value-formatting-possible-missing-semicolon-for-keyword-content/4865

After checking for the fix for https://github.com/woundride/pawpatrules/issues/1 and grep'ing the rules dir, I think that signature `3321316` is still missing the semicolon. - But didn't find any other occurrences, at least not with that pattern.

**Comment by woundride** [comment]
Fixed.

Thank you Ju !
