### ISSUE TITLE
Error in SID sid:3321401

### ISSUE THREAD

**Issue by FumbleNL** [woundride/pawpatrules#3]
![Screenshot 2024-11-26 08 52 51](https://github.com/user-attachments/assets/77ebd63a-48aa-4ad6-a747-f3047205f179)
Hi, I am getting a previous sticky buffer has no matches error for sid:3321401 when performing a suricata-update. verified this on two different systems.

**Comment by BeatriceW** [comment]
Error on same SID -- 

error parsing signature "alert tls $HOME_NET any -> $EXTERNAL_NET any (msg:"🐾 - ℹ Thunderbird 🕊 Email client 📧"; flow:to_
server, stateless;threshold: type limit, track by_src,count 1, seconds 86400; tls_sni; ja3.hash; content:"6491a9b7af75bb7b7d6fa288f3ebc217"; reference:url,https://www.thunderbird.net/; metadata:created_at 2024_11_06, updated_at 2024_11_06; sid:3321401; rev:1; classtype:misc-activity;)"

**Comment by woundride** [comment]
Hi,
Thank you for your alert !
I've found the issue, it's corrected.
Can you update ruleset and confirm it's OK for you please ?

**Comment by FumbleNL** [comment]
Works for me. Thank you for the quick fix. Keep up the good work!
